name: Test actions environment
on:
  push:
      paths:
          - '.github/workflows/**'
          - 'cicd-section/api/**' 
permissions:
    id-token: write
    contents: read
jobs:
  # Test
  test:
      runs-on: ubuntu-latest
      steps:
          # Checkout code
          - uses: actions/checkout@v4
          - name: ひとまずテスト
            run: |
              echo GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}
              echo GITHUB_OUTPUT = ${GITHUB_OUTPUT}
  build:
      runs-on: ubuntu-latest
      steps:
          # Checkout code
          - uses: actions/checkout@v4
          - name: 次にビルド
            run: |
              echo GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}
              echo GITHUB_OUTPUT = ${GITHUB_OUTPUT}
